# launcher name & url
launcher_name=ZalithLauncher
launcher_app_name=Zalith Launcher
launcher_short_name=ZL2
url_home=https://github.com/sharath-5br2r/ZalithLauncher2-Extra

# your OAuth client id
# Using the public Xbox device-code client ID compatible with login.live.com refresh flow
oauth_client_id=3936adb1-e7bb-4d7b-9951-112adae5341c

# curseforge official launcher key
curseforge_api_key=$2a$10$bL4bIL5pUWqfcO7KQtnMReakwtfHbNKh6v1uTpKlzhwoueEJQnPnm

# default key, please add it yourself.
default_store_password=vh#nn%N(#eNjwfA78-77s6&f-cdd(@-7eana-e%!nhj%))!@c
default_key_password=sfv72ghSSNQaadf99-Q69!2

# launcher version
launcher_version_code=200044
launcher_version_name=2.7


